# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:
  mysql_db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'testdatabase'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app-tier

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    networks:
      - app-tier
    command:
      tail -f /dev/null

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge